In [ ]:
import pandas as pd
import numpy as np                                        #kodlamaya başlamadan önce gerekli kütüphaneleri sayfama dahil ediyorum
from sklearn.linear_model import LinearRegression

In [ ]:
dfC = pd.read_csv("basitDogrusalRegresyonVeriSeti.csv")   #veri setini sayfaya dahil ediyoruz

In [ ]:
df = dfC.copy()     #ana datayı bozmamak için bir kopyasını oluşturduk ve işlemlerimizi bunun üzerinden gerçekleştireceğiz

In [ ]:
df.head(3)     #ilk üç gözlem değerimi alıyorum

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27

In [ ]:
df.tail(3)      #son üç gözlem değerimi alıyorum

Hours  Scores
22    3.8      35
23    6.9      76
24    7.8      86

In [ ]:
df.info()          #veri seti hakkında kısa bilgi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 528.0 bytes


In [ ]:
df.describe().T       #veri setinin istatistiksel bilgisini alıyoruz

count    mean        std   min   25%   50%   75%   max
Hours    25.0   5.012   2.525094   1.1   2.7   4.8   7.4   9.2
Scores   25.0  51.480  25.286887  17.0  30.0  47.0  75.0  95.0

In [ ]:
df.isnull().sum()         #veri seti içerisinde boş değer olup olmadığını gözlemliyoruz

Hours     0
Scores    0
dtype: int64

In [ ]:
df.duplicated().sum()    #tekrarlanan satırların değerini bize verir

0

In [ ]:
df.shape    #shape değeri veri setinin satır ve sütün sayısını göstermektedir

(25, 2)

In [ ]:
df.columns  #bu ifade veri setinin kolonlarını getirir

Index(['Hours', 'Scores'], dtype='object')

In [ ]:
y = df[["Scores"]]             #burada model kurmadan önce bağımlı ve bağımsız değişkenlerimizi oluşturuyoruz
x = df[["Hours"]]

In [ ]:
lr = LinearRegression()              #modelimizi çağırıyoruz

In [ ]:
model = lr.fit(x,y)                   #modelimizi eğitiyoruz (fit)

In [ ]:
model.coef_                          #modelin katsayısını alıyoruz

array([[9.77580339]])

In [ ]:
model.intercept_                    #modelin sabit değerini alıyoruz

array([2.48367341])

In [ ]:
model.score(x,y)                      #modelin ahminlerinin doğruluğunu veya performansını ölçen bir değerlendirme ölçütüdür

0.9529481969048356

In [ ]:
model.predict([[8]])                 #modelde tahminleme yapar (örneğin burada 8 saat çalışan birinin kaç puan alacağı tahmin edilmiştir)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[80.69010053]])